version: '3.7'

services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    ports:
       - "3002:3002"
    environment:
      MYSQL_USERNAME: admin
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: master
    volumes:
      - ./:/app
  mysqlDB:
    platform: linux/x86_64
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: master